theme: jekyll-theme-cayman
title: "March Madness Prediction Challenge"
description: "Machine learning models to predict NCAA basketball tournament outcomes"
show_downloads: true
google_analytics: 
github:
  repository_url: https://github.com/yourusername/march-madness-prediction
  is_project_page: true
  owner_name: Ethan Perello
  repository_name: march-madness-prediction

# Navigation
nav:
  - title: Home
    url: /march-madness-prediction/
  - title: Methodology
    url: /march-madness-prediction/methodology
  - title: Results
    url: /march-madness-prediction/results
  - title: Code
    url: /march-madness-prediction/code

# Basic site settings
baseurl: "/march-madness-prediction"
authors: "Ethan Perello & Samuel Kellum"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Methodology
    url: /methodology
  - title: Models & Results
    url: /results
  - title: Code & Implementation
    url: /code
  - title: GitHub
    url: https://github.com/yourusername/march-madness-prediction